---
title: 'Blue Mesa: Data Cleaning'
author: "Stephanie Kinser"
date: '2022-03-29'
output: pdf_document
---

```{r setup, include=FALSE}
getwd()

#install.packages("tidyverse")
library(tidyverse)
#install.packages("dplyr")
library(dplyr)
#install.packages("lubridate")
library(lubridate)
#install.packages("naniar")
library(naniar)


```

```{r read data}

climate <- read.csv("../Data/Raw/BlueMesa_Climate.csv")
power <- read.csv("../Data/Raw/BLUEMESAPOWERPLANT.csv")
res <- read.csv("../Data/Raw/BLUEMESARESERVOIR.csv")

```

```{r climate}

climate <- climate %>%
  rename(Date = ï..Date)%>%
  replace_with_na(replace = list(Precip = c("M", "T"),
                                 Snow = c("M", "T")))

climate$Date <- as.Date(climate$Date, format = "%Y-%m")
climate$MaxT <- as.numeric(climate$MaxT)
climate$MinT <- as.numeric(climate$MinT)
climate$Precip <- as.numeric(climate$Precip)
climate$Snow <- as.numeric(climate$Snow)

```

```{r power}

power <- power %>%
  rename(Date = ï..Date)%>%
  subset(select = c(Date, MWH))

power$Date <- gsub("1-", "01-", as.character(power$Date))

power$Date <- as.Date(power$Date, format = "%d-%b-%y")


```


```{r reservoir}

res <- res %>%
  rename(Date = ï..Date,
         Elevation = Elevation..feet.,
         Storage = Storage..af.,
         Evaporation = Evaporation..af.,
         Inflow = Inflow....cfs.,
         UnregInflow = Unregulated.Inflow.....cfs.,
         Power = Power.Release..cfs.,
         Bypass = Bypass.Release..cfs.,
         Spillway = Spillway.Release..cfs.,
         Total = Total.Release..cfs.) %>%
  subset(select = c(Date:Total))

res$Date <- gsub("1-", "01-", as.character(res$Date))

res$Date <- as.Date(res$Date, format = "%d-%b-%y")
```
 
 
```{r}
write.csv(climate, row.names = FALSE, file = "../Data/Processed/BlueMesaClimate.csv")

write.csv(power, row.names = FALSE, file = "../Data/Processed/BlueMesaPower.csv")

write.csv(res, row.names = FALSE, file = "../Data/Processed/BlueMesaReservoir.csv")
```

 